services:
  - type: web
    name: parcial-alumnos
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn Parcial.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Parcial.settings
      - key: PYTHON_VERSION
        value: 3.11
